title: hari's homepage
author: hari sankar
email: your-email@domain.com
#theme: jekyll-theme-minimal
baseurl: ""
remote_theme: nformatic/plainwhite-jekyll

plainwhite:
  title: hari's homepage
  name: hari sankar
  tagline: Naval Architect Developer. Designer
  portfolio_image: "assets/capture.jpg"
  date_format: "%b %-d, %Y"

  social_links:
    twitter: _______hari
    github: nformatic
    #linkedIn: in/samarsault # format: locale/username
