title: hari's homepage
author: hari sankar
email: your-email@domain.com
#theme: jekyll-theme-minimal
baseurl: ""
remote_theme: informatikz/plainwhite-jekyll

plainwhite:
  name: Adam Denisov
  tagline: Developer. Designer
  date_format: "%b %-d, %Y"

  social_links:
    twitter: hari_______
    github: informatikz
    #linkedIn: in/samarsault # format: locale/username