title: hari's homepage
author: hari sankar
email: your-email@domain.com
#theme: jekyll-theme-minimal
baseurl: ""
remote_theme: informatikz/plainwhite-jekyll

plainwhite:
  name: hari sankar
  tagline: Naval Architect Developer. Designer
  portfolio_image: assets/Capture.png
  date_format: "%b %-d, %Y"

  social_links:
    twitter: hari_______
    github: informatikz
    #linkedIn: in/samarsault # format: locale/username